pc/rb - changes to fix a problem with Gradescope autograder
Gradescope autograder for team01 was failing with the
error:

java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.context.ApplicationContextException: Failed to start bean documentationPluginsBootstrapper; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null

The fix was found by Prof. Conrad and tested by Robert Briggs, and comes
from this stack overflow answer:

https://stackoverflow.com/a/70892119